### ISSUE TITLE
no module named mujoco

### ISSUE THREAD

**Issue by papercut-linkin** [deepmind/rgb_stacking#8]
hi ~ thanks for your sharing.
When I was using this repo, I got a strange error 

'''
Traceback (most recent call last):
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lwt/github_test/rgb_stacking/rgb_stacking/main.py", line 116, in <module>
    app.run(main)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/lwt/github_test/rgb_stacking/rgb_stacking/main.py", line 85, in main
    with environment.rgb_stacking(object_triplet=_OBJECT_TRIPLET.value) as env:
  File "/home/lwt/github_test/rgb_stacking/rgb_stacking/environment.py", line 169, in rgb_stacking
    task_env = env_builder.build_base_env()
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_robotics/moma/subtask_env_builder.py", line 84, in build_base_env
    strip_singleton_obs_buffer_dim=True)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_control/composer/environment.py", line 304, in __init__
    strip_singleton_obs_buffer_dim=strip_singleton_obs_buffer_dim)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_control/composer/environment.py", line 203, in __init__
    self._recompile_physics_and_update_observables()
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_control/composer/environment.py", line 223, in _recompile_physics_and_update_observables
    self._hooks.after_compile(self._physics_proxy, self._random_state)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_control/composer/environment.py", line 112, in after_compile
    self._task.after_compile(physics, random_state)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_robotics/moma/base_task.py", line 200, in after_compile
    ef.after_compile(self.root_entity.mjcf_model.root)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_robotics/moma/effectors/constrained_actions_effectors.py", line 110, in after_compile
    self._delegate.after_compile(mjcf_model)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_robotics/moma/effectors/cartesian_4d_velocity_effector.py", line 150, in after_compile
    self._effector_6d.after_compile(mjcf_model)
  File "/home/lwt/anaconda3/envs/rgb/lib/python3.7/site-packages/dm_robotics/moma/effectors/cartesian_6d_velocity_effector.py", line 363, in after_compile
    qp_params = _CartesianVelocityMapperParams()
ModuleNotFoundError: No module named 'mujoco'
'''
I'm pretty sure mujoco is installed correctly 
'''
export MUJOCO_GL="glfw"
export MJLIB_PATH=$HOME/.mujoco/mujoco200/bin/libmujoco200.so
export MJKEY_PATH=$HOME/.mujoco/mujoco200/mjkey.txt
export LD_LIBRARY_PATH=$HOME/.mujoco/mujoco200/bin:$LD_LIBRARY_PATH
export MUJOCO_PY_MJPRO_PATH=$HOME/.mujoco/mujoco200/
export MUJOCO_PY_MJKEY_PATH=$HOME/.mujoco/mujoco200/mjkey.txt
'''
Can you offer me some suggestions?

**Comment by SheepIWreath** [comment]
have you solved this problem now?  T ...T

**Comment by shacklestone** [comment]
Could you list the packages installed, please?
The stacktrace includes anaconda, so I guess this means running:

```
conda list
pip list
```
