### ISSUE TITLE
Mujoco not found

### ISSUE THREAD

**Issue by jangirrishabh** [deepmind/rgb_stacking#9]
Hi, can you please advice against this import error

Traceback (most recent call last):
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rishabh/workspace/rgb_stacking/rgb_stacking/main.py", line 116, in <module>
    app.run(main)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/rishabh/workspace/rgb_stacking/rgb_stacking/main.py", line 85, in main
    with environment.rgb_stacking(object_triplet=_OBJECT_TRIPLET.value) as env:
  File "/home/rishabh/workspace/rgb_stacking/rgb_stacking/environment.py", line 169, in rgb_stacking
    task_env = env_builder.build_base_env()
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_robotics/moma/subtask_env_builder.py", line 83, in build_base_env
    self._base_env = composer.Environment(self._task,
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_control/composer/environment.py", line 298, in __init__
    super().__init__(
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_control/composer/environment.py", line 203, in __init__
    self._recompile_physics_and_update_observables()
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_control/composer/environment.py", line 223, in _recompile_physics_and_update_observables
    self._hooks.after_compile(self._physics_proxy, self._random_state)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_control/composer/environment.py", line 112, in after_compile
    self._task.after_compile(physics, random_state)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_robotics/moma/base_task.py", line 200, in after_compile
    ef.after_compile(self.root_entity.mjcf_model.root)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_robotics/moma/effectors/constrained_actions_effectors.py", line 110, in after_compile
    self._delegate.after_compile(mjcf_model)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_robotics/moma/effectors/cartesian_4d_velocity_effector.py", line 150, in after_compile
    self._effector_6d.after_compile(mjcf_model)
  File "/home/rishabh/anaconda3/envs/rgb_stacking/lib/python3.9/site-packages/dm_robotics/moma/effectors/cartesian_6d_velocity_effector.py", line 363, in after_compile
    qp_params = _CartesianVelocityMapperParams()
ModuleNotFoundError: No module named 'mujoco'

**Comment by shacklestone** [comment]
This looks like a duplicate of https://github.com/deepmind/rgb_stacking/issues/8
